openapi: 3.1.0
info:
  title: 'Amazon Storage Gateway REST Amazon Storage Gateway REST API #X Amz Target=StorageGateway 20130630.UpdateVTLDeviceType API'
  description: AWS Storage Gateway is a hybrid cloud storage service that gives you on-premises access to virtually unlimited cloud storage. This API enables management of gateways, volumes, virtual tapes, file shares, and cached storage resources.
  version: '2013-06-30'
  contact:
    name: AWS Support
    url: https://aws.amazon.com/premiumsupport/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://aws.amazon.com/service-terms/
  x-logo:
    url: https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x630.png
servers:
- url: https://storagegateway.{region}.amazonaws.com
  description: Amazon Storage Gateway regional endpoint
  variables:
    region:
      default: us-east-1
      description: AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - eu-west-1
      - eu-west-2
      - eu-central-1
      - ap-northeast-1
      - ap-southeast-1
      - ap-southeast-2
      - ap-south-1
      - sa-east-1
security:
- sigv4: []
tags:
- name: '#X Amz Target=StorageGateway 20130630.UpdateVTLDeviceType'
paths:
  /#X-Amz-Target=StorageGateway_20130630.UpdateVTLDeviceType:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: UpdateVTLDeviceType
      description: Updates the type of medium changer in a tape gateway. When you activate a tape gateway, you select a medium changer type for the tape gateway. This operation enables you to select a different type of medium changer after a tape gateway is activated. This operation is only supported in the tape gateway type.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateVTLDeviceTypeOutput'
        '480':
          description: InvalidGatewayRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidGatewayRequestException'
        '481':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateVTLDeviceTypeInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - StorageGateway_20130630.UpdateVTLDeviceType
      tags:
      - '#X Amz Target=StorageGateway 20130630.UpdateVTLDeviceType'
components:
  schemas:
    InternalServerError: {}
    InvalidGatewayRequestException: {}
    VTLDeviceARN:
      type: string
      minLength: 50
      maxLength: 500
    DeviceType:
      type: string
      minLength: 2
      maxLength: 50
    UpdateVTLDeviceTypeInput:
      type: object
      required:
      - VTLDeviceARN
      - DeviceType
      title: UpdateVTLDeviceTypeInput
      properties:
        VTLDeviceARN:
          allOf:
          - $ref: '#/components/schemas/VTLDeviceARN'
          - description: The Amazon Resource Name (ARN) of the medium changer you want to select.
        DeviceType:
          allOf:
          - $ref: '#/components/schemas/DeviceType'
          - description: '<p>The type of medium changer you want to select.</p> <p>Valid Values: <code>STK-L700</code> | <code>AWS-Gateway-VTL</code> | <code>IBM-03584L32-0402</code> </p>'
    UpdateVTLDeviceTypeOutput:
      type: object
      example:
        VTLDeviceARN: arn:aws:storagegateway:us-east-1:999999999999:gateway/sgw-12A3456B/device/AMZN_SGW-1FAD4876_MEDIACHANGER_00001
      properties:
        VTLDeviceARN:
          allOf:
          - $ref: '#/components/schemas/VTLDeviceARN'
          - description: The Amazon Resource Name (ARN) of the medium changer you have selected.
      description: UpdateVTLDeviceTypeOutput
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    sigv4:
      type: apiKey
      name: Authorization
      in: header
      description: AWS Signature Version 4
externalDocs:
  description: Amazon Storage Gateway API Reference
  url: https://docs.aws.amazon.com/storagegateway/latest/APIReference/Welcome.html
