openapi: 3.2.0
info:
  version: '2013-06-30'
  x-release: v4
  title: 'AWS Storage Gateway #X Amz Target=StorageGateway 20130630.DescribeGatewayInformation API'
  description: '<fullname>Storage Gateway Service</fullname> <p>Storage Gateway is the service that connects an on-premises software appliance with cloud-based storage to provide seamless and secure integration between an organization''s on-premises IT environment and the Amazon Web Services storage infrastructure. The service enables you to securely upload data to the Amazon Web Services Cloud for cost effective backup and rapid disaster recovery.</p> <p>Use the following links to get started using the <i>Storage Gateway Service API Reference</i>:</p> <ul> <li> <p> <a href="https://docs.aws.amazon.com/storagegateway/latest/userguide/AWSStorageGatewayAPI.html#AWSStorageGatewayHTTPRequestsHeaders">Storage Gateway required request headers</a>: Describes the required headers that you must send with every POST request to Storage Gateway.</p> </li> <li> <p> <a href="https://docs.aws.amazon.com/storagegateway/latest/userguide/AWSStorageGatewayAPI.html#AWSStorageGatewaySigningRequests">Signing requests</a>: Storage Gateway requires that you authenticate every request you send; this topic describes how sign such a request.</p> </li> <li> <p> <a href="https://docs.aws.amazon.com/storagegateway/latest/userguide/AWSStorageGatewayAPI.html#APIErrorResponses">Error responses</a>: Provides reference information about Storage Gateway errors.</p> </li> <li> <p> <a href="https://docs.aws.amazon.com/storagegateway/latest/APIReference/API_Operations.html">Operations in Storage Gateway</a>: Contains detailed descriptions of all Storage Gateway operations, their request parameters, response elements, possible errors, and examples of requests and responses.</p> </li> <li> <p> <a href="https://docs.aws.amazon.com/general/latest/gr/sg.html">Storage Gateway endpoints and quotas</a>: Provides a list of each Amazon Web Services Region and the endpoints available for use with Storage Gateway.</p> </li> </ul> <note> <p>Storage Gateway resource IDs are in uppercase. When you use these resource IDs with the Amazon EC2 API, EC2 expects resource IDs in lowercase. You must change your resource ID to lowercase to use it with the EC2 API. For example, in Storage Gateway the ID for a volume might be <code>vol-AA22BB012345DAF670</code>. When you use this ID with the EC2 API, you must change it to <code>vol-aa22bb012345daf670</code>. Otherwise, the EC2 API might not behave as expected.</p> </note> <important> <p>IDs for Storage Gateway volumes and Amazon EBS snapshots created from gateway volumes are changing to a longer format. Starting in December 2016, all new volumes and snapshots will be created with a 17-character string. Starting in April 2016, you will be able to use these longer IDs so you can test your systems with the new format. For more information, see <a href="http://aws.amazon.com/ec2/faqs/#longer-ids">Longer EC2 and EBS resource IDs</a>.</p> <p>For example, a volume Amazon Resource Name (ARN) with the longer volume ID format looks like the following:</p> <p> <code>arn:aws:storagegateway:us-west-2:111122223333:gateway/sgw-12A3456B/volume/vol-1122AABBCCDDEEFFG</code>.</p> <p>A snapshot ID with the longer ID format looks like the following: <code>snap-78e226633445566ee</code>.</p> <p>For more information, see <a href="http://forums.aws.amazon.com/ann.jspa?annID=3557">Announcement: Heads-up – Longer Storage Gateway volume and snapshot IDs coming in 2016</a>.</p> </important>'
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: storagegateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/storagegateway-2013-06-30.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://storagegateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Storage Gateway multi-region endpoint
- url: https://storagegateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Storage Gateway multi-region endpoint
- url: http://storagegateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Storage Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://storagegateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Storage Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=StorageGateway 20130630.DescribeGatewayInformation'
paths:
  /#X-Amz-Target=StorageGateway_20130630.DescribeGatewayInformation:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DescribeGatewayInformation
      description: Returns metadata about a gateway such as its name, network interfaces, configured time zone, and the state (whether the gateway is running or not). To specify which gateway to describe, use the Amazon Resource Name (ARN) of the gateway in your request.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeGatewayInformationOutput'
        '480':
          description: InvalidGatewayRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidGatewayRequestException'
        '481':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DescribeGatewayInformationInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - StorageGateway_20130630.DescribeGatewayInformation
      tags:
      - '#X Amz Target=StorageGateway 20130630.DescribeGatewayInformation'
components:
  schemas:
    InternalServerError: {}
    HostEnvironmentId:
      type: string
      minLength: 1
      maxLength: 1024
    LastSoftwareUpdate:
      type: string
      minLength: 1
      maxLength: 25
    CloudWatchLogGroupARN:
      type: string
      maxLength: 562
    GatewayCapacity:
      type: string
      enum:
      - Small
      - Medium
      - Large
    SupportedGatewayCapacities:
      type: array
      items:
        $ref: '#/components/schemas/GatewayCapacity'
    Ec2InstanceRegion:
      type: string
    DescribeGatewayInformationOutput:
      type: object
      example:
        GatewayARN: arn:aws:storagegateway:us-east-1:111122223333:gateway/sgw-12A3456B
        GatewayId: sgw-AABB1122
        GatewayName: My_Gateway
        GatewayNetworkInterfaces:
        - Ipv4Address: 10.35.69.216
        GatewayState: STATE_RUNNING
        GatewayTimezone: GMT-8:00
        GatewayType: STORED
        LastSoftwareUpdate: '2016-01-02T16:00:00'
        NextUpdateAvailabilityDate: '2017-01-02T16:00:00'
      properties:
        GatewayARN:
          $ref: '#/components/schemas/GatewayARN'
        GatewayId:
          allOf:
          - $ref: '#/components/schemas/GatewayId'
          - description: The unique identifier assigned to your gateway during activation. This ID becomes part of the gateway Amazon Resource Name (ARN), which you use as input for other operations.
        GatewayName:
          allOf:
          - $ref: '#/components/schemas/string'
          - description: The name you configured for your gateway.
        GatewayTimezone:
          allOf:
          - $ref: '#/components/schemas/GatewayTimezone'
          - description: A value that indicates the time zone configured for the gateway.
        GatewayState:
          allOf:
          - $ref: '#/components/schemas/GatewayState'
          - description: A value that indicates the operating state of the gateway.
        GatewayNetworkInterfaces:
          allOf:
          - $ref: '#/components/schemas/GatewayNetworkInterfaces'
          - description: A <a>NetworkInterface</a> array that contains descriptions of the gateway network interfaces.
        GatewayType:
          allOf:
          - $ref: '#/components/schemas/GatewayType'
          - description: The type of the gateway.
        NextUpdateAvailabilityDate:
          allOf:
          - $ref: '#/components/schemas/NextUpdateAvailabilityDate'
          - description: The date on which an update to the gateway is available. This date is in the time zone of the gateway. If the gateway is not available for an update this field is not returned in the response.
        LastSoftwareUpdate:
          allOf:
          - $ref: '#/components/schemas/LastSoftwareUpdate'
          - description: The date on which the last software update was applied to the gateway. If the gateway has never been updated, this field does not return a value in the response. This only only exist and returns once it have been chosen and set by the SGW service, based on the OS version of the gateway VM
        Ec2InstanceId:
          allOf:
          - $ref: '#/components/schemas/Ec2InstanceId'
          - description: The ID of the Amazon EC2 instance that was used to launch the gateway.
        Ec2InstanceRegion:
          allOf:
          - $ref: '#/components/schemas/Ec2InstanceRegion'
          - description: The Amazon Web Services Region where the Amazon EC2 instance is located.
        Tags:
          allOf:
          - $ref: '#/components/schemas/Tags'
          - description: A list of up to 50 tags assigned to the gateway, sorted alphabetically by key name. Each tag is a key-value pair. For a gateway with more than 10 tags assigned, you can view all tags using the <code>ListTagsForResource</code> API operation.
        VPCEndpoint:
          allOf:
          - $ref: '#/components/schemas/string'
          - description: The configuration settings for the virtual private cloud (VPC) endpoint for your gateway.
        CloudWatchLogGroupARN:
          allOf:
          - $ref: '#/components/schemas/CloudWatchLogGroupARN'
          - description: The Amazon Resource Name (ARN) of the Amazon CloudWatch log group that is used to monitor events in the gateway. This field only only exist and returns once it have been chosen and set by the SGW service, based on the OS version of the gateway VM
        HostEnvironment:
          allOf:
          - $ref: '#/components/schemas/HostEnvironment'
          - description: The type of hardware or software platform on which the gateway is running.
        EndpointType:
          allOf:
          - $ref: '#/components/schemas/EndpointType'
          - description: '<p>The type of endpoint for your gateway.</p> <p>Valid Values: <code>STANDARD</code> | <code>FIPS</code> </p>'
        SoftwareUpdatesEndDate:
          allOf:
          - $ref: '#/components/schemas/SoftwareUpdatesEndDate'
          - description: Date after which this gateway will not receive software updates for new features.
        DeprecationDate:
          allOf:
          - $ref: '#/components/schemas/DeprecationDate'
          - description: Date after which this gateway will not receive software updates for new features and bug fixes.
        GatewayCapacity:
          allOf:
          - $ref: '#/components/schemas/GatewayCapacity'
          - description: Specifies the size of the gateway's metadata cache.
        SupportedGatewayCapacities:
          allOf:
          - $ref: '#/components/schemas/SupportedGatewayCapacities'
          - description: A list of the metadata cache sizes that the gateway can support based on its current hardware specifications.
        HostEnvironmentId:
          allOf:
          - $ref: '#/components/schemas/HostEnvironmentId'
          - description: A unique identifier for the specific instance of the host platform running the gateway. This value is only available for certain host environments, and its format depends on the host environment type.
      description: 'A JSON object containing the following fields:'
    DeprecationDate:
      type: string
      minLength: 1
      maxLength: 25
    GatewayNetworkInterfaces:
      type: array
      items:
        $ref: '#/components/schemas/NetworkInterface'
    NextUpdateAvailabilityDate:
      type: string
      minLength: 1
      maxLength: 25
    InvalidGatewayRequestException: {}
    GatewayTimezone:
      type: string
      minLength: 3
      maxLength: 10
    string:
      type: string
    TagValue:
      type: string
      maxLength: 256
    TagKey:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 1
      maxLength: 128
    EndpointType:
      type: string
      minLength: 4
      maxLength: 8
    HostEnvironment:
      type: string
      enum:
      - VMWARE
      - HYPER-V
      - EC2
      - KVM
      - OTHER
      - SNOWBALL
    GatewayARN:
      type: string
      description: The Amazon Resource Name (ARN) of the gateway. Use the <a>ListGateways</a> operation to return a list of gateways for your account and Amazon Web Services Region.
      minLength: 50
      maxLength: 500
    GatewayState:
      type: string
      minLength: 2
      maxLength: 25
    Ec2InstanceId:
      type: string
    GatewayType:
      type: string
      minLength: 2
      maxLength: 20
    Tags:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    NetworkInterface:
      type: object
      properties:
        Ipv4Address:
          allOf:
          - $ref: '#/components/schemas/string'
          - description: The Internet Protocol version 4 (IPv4) address of the interface.
        MacAddress:
          allOf:
          - $ref: '#/components/schemas/string'
          - description: <p>The Media Access Control (MAC) address of the interface.</p> <note> <p>This is currently unsupported and will not be returned in output.</p> </note>
        Ipv6Address:
          allOf:
          - $ref: '#/components/schemas/string'
          - description: The Internet Protocol version 6 (IPv6) address of the interface. <i>Currently not supported</i>.
      description: Describes a gateway's network interface.
    SoftwareUpdatesEndDate:
      type: string
      minLength: 1
      maxLength: 25
    DescribeGatewayInformationInput:
      type: object
      required:
      - GatewayARN
      title: DescribeGatewayInformationInput
      properties:
        GatewayARN:
          $ref: '#/components/schemas/GatewayARN'
      description: A JSON object containing the ID of the gateway.
    Tag:
      type: object
      required:
      - Key
      - Value
      properties:
        Key:
          allOf:
          - $ref: '#/components/schemas/TagKey'
          - description: Tag key. The key can't start with aws:.
        Value:
          allOf:
          - $ref: '#/components/schemas/TagValue'
          - description: Value of the tag key.
      description: 'A key-value pair that helps you manage, filter, and search for your resource. Allowed characters: letters, white space, and numbers, representable in UTF-8, and the following characters: + - = . _ : /.'
    GatewayId:
      type: string
      minLength: 12
      maxLength: 30
  parameters:
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/storagegateway/
x-hasEquivalentPaths: true
