openapi: 3.1.0
info:
  title: 'Amazon Storage Gateway REST Amazon Storage Gateway REST API #X Amz Target=StorageGateway 20130630.DescribeBandwidthRateLimitSchedule API'
  description: AWS Storage Gateway is a hybrid cloud storage service that gives you on-premises access to virtually unlimited cloud storage. This API enables management of gateways, volumes, virtual tapes, file shares, and cached storage resources.
  version: '2013-06-30'
  contact:
    name: AWS Support
    url: https://aws.amazon.com/premiumsupport/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://aws.amazon.com/service-terms/
  x-logo:
    url: https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x630.png
servers:
- url: https://storagegateway.{region}.amazonaws.com
  description: Amazon Storage Gateway regional endpoint
  variables:
    region:
      default: us-east-1
      description: AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - eu-west-1
      - eu-west-2
      - eu-central-1
      - ap-northeast-1
      - ap-southeast-1
      - ap-southeast-2
      - ap-south-1
      - sa-east-1
security:
- sigv4: []
tags:
- name: '#X Amz Target=StorageGateway 20130630.DescribeBandwidthRateLimitSchedule'
paths:
  /#X-Amz-Target=StorageGateway_20130630.DescribeBandwidthRateLimitSchedule:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DescribeBandwidthRateLimitSchedule
      description: <p> Returns information about the bandwidth rate limit schedule of a gateway. By default, gateways do not have bandwidth rate limit schedules, which means no bandwidth rate limiting is in effect. This operation is supported only for volume, tape and S3 file gateways. FSx file gateways do not support bandwidth rate limits.</p> <p>This operation returns information about a gateway's bandwidth rate limit schedule. A bandwidth rate limit schedule consists of one or more bandwidth rate limit intervals. A bandwidth rate limit interval defines a period of time on one or more days of the week, during which bandwidth rate limits are specified for uploading, downloading, or both. </p> <p> A bandwidth rate limit interval consists of one or more days of the week, a start hour and minute, an ending hour and minute, and bandwidth rate limits for uploading and downloading </p> <p> If no bandwidth rate limit schedule intervals are set for the gateway, this operation returns an empty response. To specify which gateway to describe, use the Amazon Resource Name (ARN) of the gateway in your request.</p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeBandwidthRateLimitScheduleOutput'
        '480':
          description: InvalidGatewayRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidGatewayRequestException'
        '481':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DescribeBandwidthRateLimitScheduleInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - StorageGateway_20130630.DescribeBandwidthRateLimitSchedule
      tags:
      - '#X Amz Target=StorageGateway 20130630.DescribeBandwidthRateLimitSchedule'
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  schemas:
    BandwidthRateLimitIntervals:
      type: array
      items:
        $ref: '#/components/schemas/BandwidthRateLimitInterval'
      minItems: 0
      maxItems: 20
    BandwidthRateLimitInterval:
      type: object
      required:
      - StartHourOfDay
      - StartMinuteOfHour
      - EndHourOfDay
      - EndMinuteOfHour
      - DaysOfWeek
      properties:
        StartHourOfDay:
          allOf:
          - $ref: '#/components/schemas/HourOfDay'
          - description: ' The hour of the day to start the bandwidth rate limit interval. '
        StartMinuteOfHour:
          allOf:
          - $ref: '#/components/schemas/MinuteOfHour'
          - description: ' The minute of the hour to start the bandwidth rate limit interval. The interval begins at the start of that minute. To begin an interval exactly at the start of the hour, use the value <code>0</code>. '
        EndHourOfDay:
          allOf:
          - $ref: '#/components/schemas/HourOfDay'
          - description: ' The hour of the day to end the bandwidth rate limit interval. '
        EndMinuteOfHour:
          allOf:
          - $ref: '#/components/schemas/MinuteOfHour'
          - description: <p> The minute of the hour to end the bandwidth rate limit interval. </p> <important> <p> The bandwidth rate limit interval ends at the end of the minute. To end an interval at the end of an hour, use the value <code>59</code>. </p> </important>
        DaysOfWeek:
          allOf:
          - $ref: '#/components/schemas/DaysOfWeek'
          - description: ' The days of the week component of the bandwidth rate limit interval, represented as ordinal numbers from 0 to 6, where 0 represents Sunday and 6 represents Saturday. '
        AverageUploadRateLimitInBitsPerSec:
          allOf:
          - $ref: '#/components/schemas/BandwidthUploadRateLimit'
          - description: ' The average upload rate limit component of the bandwidth rate limit interval, in bits per second. This field does not appear in the response if the upload rate limit is not set. '
        AverageDownloadRateLimitInBitsPerSec:
          allOf:
          - $ref: '#/components/schemas/BandwidthDownloadRateLimit'
          - description: ' The average download rate limit component of the bandwidth rate limit interval, in bits per second. This field does not appear in the response if the download rate limit is not set. '
      description: ' Describes a bandwidth rate limit interval for a gateway. A bandwidth rate limit schedule consists of one or more bandwidth rate limit intervals. A bandwidth rate limit interval defines a period of time on one or more days of the week, during which bandwidth rate limits are specified for uploading, downloading, or both. '
    GatewayARN:
      type: string
      description: The Amazon Resource Name (ARN) of the gateway. Use the <a>ListGateways</a> operation to return a list of gateways for your account and Amazon Web Services Region.
      minLength: 50
      maxLength: 500
    InvalidGatewayRequestException: {}
    BandwidthUploadRateLimit:
      type: integer
      minimum: 51200
    DaysOfWeek:
      type: array
      items:
        $ref: '#/components/schemas/DayOfWeek'
      minItems: 1
      maxItems: 7
    DescribeBandwidthRateLimitScheduleOutput:
      type: object
      properties:
        GatewayARN:
          $ref: '#/components/schemas/GatewayARN'
        BandwidthRateLimitIntervals:
          allOf:
          - $ref: '#/components/schemas/BandwidthRateLimitIntervals'
          - description: ' An array that contains the bandwidth rate limit intervals for a tape or volume gateway. '
    HourOfDay:
      type: integer
      minimum: 0
      maximum: 23
    MinuteOfHour:
      type: integer
      minimum: 0
      maximum: 59
    DayOfWeek:
      type: integer
      minimum: 0
      maximum: 6
    DescribeBandwidthRateLimitScheduleInput:
      type: object
      required:
      - GatewayARN
      title: DescribeBandwidthRateLimitScheduleInput
      properties:
        GatewayARN:
          $ref: '#/components/schemas/GatewayARN'
    InternalServerError: {}
    BandwidthDownloadRateLimit:
      type: integer
      minimum: 102400
  securitySchemes:
    sigv4:
      type: apiKey
      name: Authorization
      in: header
      description: AWS Signature Version 4
externalDocs:
  description: Amazon Storage Gateway API Reference
  url: https://docs.aws.amazon.com/storagegateway/latest/APIReference/Welcome.html
