openapi: 3.1.0
info:
  title: 'Amazon Storage Gateway REST Amazon Storage Gateway REST API #X Amz Target=StorageGateway 20130630.DescribeTapeArchives API'
  description: AWS Storage Gateway is a hybrid cloud storage service that gives you on-premises access to virtually unlimited cloud storage. This API enables management of gateways, volumes, virtual tapes, file shares, and cached storage resources.
  version: '2013-06-30'
  contact:
    name: AWS Support
    url: https://aws.amazon.com/premiumsupport/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://aws.amazon.com/service-terms/
  x-logo:
    url: https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x630.png
servers:
- url: https://storagegateway.{region}.amazonaws.com
  description: Amazon Storage Gateway regional endpoint
  variables:
    region:
      default: us-east-1
      description: AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - eu-west-1
      - eu-west-2
      - eu-central-1
      - ap-northeast-1
      - ap-southeast-1
      - ap-southeast-2
      - ap-south-1
      - sa-east-1
security:
- sigv4: []
tags:
- name: '#X Amz Target=StorageGateway 20130630.DescribeTapeArchives'
paths:
  /#X-Amz-Target=StorageGateway_20130630.DescribeTapeArchives:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DescribeTapeArchives
      description: <p>Returns a description of specified virtual tapes in the virtual tape shelf (VTS). This operation is only supported in the tape gateway type.</p> <p>If a specific <code>TapeARN</code> is not specified, Storage Gateway returns a description of all virtual tapes found in the VTS associated with your account.</p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeTapeArchivesOutput'
        '480':
          description: InvalidGatewayRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidGatewayRequestException'
        '481':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DescribeTapeArchivesInput'
      parameters:
      - name: Limit
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: Marker
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - StorageGateway_20130630.DescribeTapeArchives
      tags:
      - '#X Amz Target=StorageGateway 20130630.DescribeTapeArchives'
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  schemas:
    PoolId:
      type: string
      minLength: 1
      maxLength: 100
    Marker:
      type: string
      minLength: 1
      maxLength: 1000
    DescribeTapeArchivesOutput:
      type: object
      example:
        Marker: '1'
        TapeArchives:
        - CompletionTime: 2016-12-16T13:50Z
          TapeARN: arn:aws:storagegateway:us-east-1:999999999:tape/AM08A1AD
          TapeBarcode: AM08A1AD
          TapeSizeInBytes: 107374182400
          TapeStatus: ARCHIVED
        - CompletionTime: 2016-12-16T13:59Z
          TapeARN: arn:aws:storagegateway:us-east-1:999999999:tape/AMZN01A2A4
          TapeBarcode: AMZN01A2A4
          TapeSizeInBytes: 429496729600
          TapeStatus: ARCHIVED
      properties:
        TapeArchives:
          allOf:
          - $ref: '#/components/schemas/TapeArchives'
          - description: An array of virtual tape objects in the virtual tape shelf (VTS). The description includes of the Amazon Resource Name (ARN) of the virtual tapes. The information returned includes the Amazon Resource Names (ARNs) of the tapes, size of the tapes, status of the tapes, progress of the description, and tape barcode.
        Marker:
          allOf:
          - $ref: '#/components/schemas/Marker'
          - description: An opaque string that indicates the position at which the virtual tapes that were fetched for description ended. Use this marker in your next request to fetch the next set of virtual tapes in the virtual tape shelf (VTS). If there are no more virtual tapes to describe, this field does not appear in the response.
      description: DescribeTapeArchivesOutput
    GatewayARN:
      type: string
      description: The Amazon Resource Name (ARN) of the gateway. Use the <a>ListGateways</a> operation to return a list of gateways for your account and Amazon Web Services Region.
      minLength: 50
      maxLength: 500
    TapeArchive:
      type: object
      properties:
        TapeARN:
          allOf:
          - $ref: '#/components/schemas/TapeARN'
          - description: The Amazon Resource Name (ARN) of an archived virtual tape.
        TapeBarcode:
          allOf:
          - $ref: '#/components/schemas/TapeBarcode'
          - description: The barcode that identifies the archived virtual tape.
        TapeCreatedDate:
          allOf:
          - $ref: '#/components/schemas/Time'
          - description: The date the virtual tape was created.
        TapeSizeInBytes:
          allOf:
          - $ref: '#/components/schemas/TapeSize'
          - description: The size, in bytes, of the archived virtual tape.
        CompletionTime:
          allOf:
          - $ref: '#/components/schemas/Time'
          - description: <p>The time that the archiving of the virtual tape was completed.</p> <p>The default timestamp format is in the ISO8601 extended YYYY-MM-DD'T'HH:MM:SS'Z' format.</p>
        RetrievedTo:
          allOf:
          - $ref: '#/components/schemas/GatewayARN'
          - description: <p>The Amazon Resource Name (ARN) of the tape gateway that the virtual tape is being retrieved to.</p> <p>The virtual tape is retrieved from the virtual tape shelf (VTS).</p>
        TapeStatus:
          allOf:
          - $ref: '#/components/schemas/TapeArchiveStatus'
          - description: The current state of the archived virtual tape.
        TapeUsedInBytes:
          allOf:
          - $ref: '#/components/schemas/TapeUsage'
          - description: <p>The size, in bytes, of data stored on the virtual tape.</p> <note> <p>This value is not available for tapes created prior to May 13, 2015.</p> </note>
        KMSKey:
          $ref: '#/components/schemas/KMSKey'
        PoolId:
          allOf:
          - $ref: '#/components/schemas/PoolId'
          - description: The ID of the pool that was used to archive the tape. The tapes in this pool are archived in the S3 storage class that is associated with the pool.
        Worm:
          allOf:
          - $ref: '#/components/schemas/boolean'
          - description: Set to <code>true</code> if the archived tape is stored as write-once-read-many (WORM).
        RetentionStartDate:
          allOf:
          - $ref: '#/components/schemas/Time'
          - description: If the archived tape is subject to tape retention lock, the date that the archived tape started being retained.
        PoolEntryDate:
          allOf:
          - $ref: '#/components/schemas/Time'
          - description: <p>The time that the tape entered the custom tape pool.</p> <p>The default timestamp format is in the ISO8601 extended YYYY-MM-DD'T'HH:MM:SS'Z' format.</p>
      description: Represents a virtual tape that is archived in the virtual tape shelf (VTS).
    InvalidGatewayRequestException: {}
    DescribeTapeArchivesInput:
      type: object
      title: DescribeTapeArchivesInput
      properties:
        TapeARNs:
          allOf:
          - $ref: '#/components/schemas/TapeARNs'
          - description: Specifies one or more unique Amazon Resource Names (ARNs) that represent the virtual tapes you want to describe.
        Marker:
          allOf:
          - $ref: '#/components/schemas/Marker'
          - description: An opaque string that indicates the position at which to begin describing virtual tapes.
        Limit:
          allOf:
          - $ref: '#/components/schemas/PositiveIntObject'
          - description: Specifies that the number of virtual tapes described be limited to the specified number.
      description: DescribeTapeArchivesInput
    TapeARN:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-us-gov):storagegateway:[a-z\-0-9]+:[0-9]+:tape\/[0-9A-Z]{5,16}$
      minLength: 50
      maxLength: 500
    PositiveIntObject:
      type: integer
      minimum: 1
    KMSKey:
      type: string
      pattern: (^arn:(aws|aws-cn|aws-us-gov):kms:([a-zA-Z0-9-]+):([0-9]+):(key|alias)/(\S+)$)|(^alias/(\S+)$)
      description: The Amazon Resource Name (ARN) of a symmetric customer master key (CMK) used for Amazon S3 server-side encryption. Storage Gateway does not support asymmetric CMKs. This value can only be set when <code>KMSEncrypted</code> is <code>true</code>. Optional.
      minLength: 7
      maxLength: 2048
    TapeSize:
      type: integer
    TapeBarcode:
      type: string
      pattern: ^[A-Z0-9]*$
      minLength: 5
      maxLength: 16
    TapeArchives:
      type: array
      items:
        $ref: '#/components/schemas/TapeArchive'
    TapeARNs:
      type: array
      description: The Amazon Resource Name (ARN) of each of the tapes you want to list. If you don't specify a tape ARN, the response lists all tapes in both your VTL and VTS.
      items:
        $ref: '#/components/schemas/TapeARN'
    InternalServerError: {}
    boolean:
      type: boolean
    TapeArchiveStatus:
      type: string
    Time:
      type: string
      format: date-time
    TapeUsage:
      type: integer
  securitySchemes:
    sigv4:
      type: apiKey
      name: Authorization
      in: header
      description: AWS Signature Version 4
externalDocs:
  description: Amazon Storage Gateway API Reference
  url: https://docs.aws.amazon.com/storagegateway/latest/APIReference/Welcome.html
