openapi: 3.2.0
info:
  version: '2013-06-30'
  x-release: v4
  title: 'AWS Storage Gateway #X Amz Target=StorageGateway 20130630.DescribeTapeArchives API'
  description: '<fullname>Storage Gateway Service</fullname> <p>Storage Gateway is the service that connects an on-premises software appliance with cloud-based storage to provide seamless and secure integration between an organization''s on-premises IT environment and the Amazon Web Services storage infrastructure. The service enables you to securely upload data to the Amazon Web Services Cloud for cost effective backup and rapid disaster recovery.</p> <p>Use the following links to get started using the <i>Storage Gateway Service API Reference</i>:</p> <ul> <li> <p> <a href="https://docs.aws.amazon.com/storagegateway/latest/userguide/AWSStorageGatewayAPI.html#AWSStorageGatewayHTTPRequestsHeaders">Storage Gateway required request headers</a>: Describes the required headers that you must send with every POST request to Storage Gateway.</p> </li> <li> <p> <a href="https://docs.aws.amazon.com/storagegateway/latest/userguide/AWSStorageGatewayAPI.html#AWSStorageGatewaySigningRequests">Signing requests</a>: Storage Gateway requires that you authenticate every request you send; this topic describes how sign such a request.</p> </li> <li> <p> <a href="https://docs.aws.amazon.com/storagegateway/latest/userguide/AWSStorageGatewayAPI.html#APIErrorResponses">Error responses</a>: Provides reference information about Storage Gateway errors.</p> </li> <li> <p> <a href="https://docs.aws.amazon.com/storagegateway/latest/APIReference/API_Operations.html">Operations in Storage Gateway</a>: Contains detailed descriptions of all Storage Gateway operations, their request parameters, response elements, possible errors, and examples of requests and responses.</p> </li> <li> <p> <a href="https://docs.aws.amazon.com/general/latest/gr/sg.html">Storage Gateway endpoints and quotas</a>: Provides a list of each Amazon Web Services Region and the endpoints available for use with Storage Gateway.</p> </li> </ul> <note> <p>Storage Gateway resource IDs are in uppercase. When you use these resource IDs with the Amazon EC2 API, EC2 expects resource IDs in lowercase. You must change your resource ID to lowercase to use it with the EC2 API. For example, in Storage Gateway the ID for a volume might be <code>vol-AA22BB012345DAF670</code>. When you use this ID with the EC2 API, you must change it to <code>vol-aa22bb012345daf670</code>. Otherwise, the EC2 API might not behave as expected.</p> </note> <important> <p>IDs for Storage Gateway volumes and Amazon EBS snapshots created from gateway volumes are changing to a longer format. Starting in December 2016, all new volumes and snapshots will be created with a 17-character string. Starting in April 2016, you will be able to use these longer IDs so you can test your systems with the new format. For more information, see <a href="http://aws.amazon.com/ec2/faqs/#longer-ids">Longer EC2 and EBS resource IDs</a>.</p> <p>For example, a volume Amazon Resource Name (ARN) with the longer volume ID format looks like the following:</p> <p> <code>arn:aws:storagegateway:us-west-2:111122223333:gateway/sgw-12A3456B/volume/vol-1122AABBCCDDEEFFG</code>.</p> <p>A snapshot ID with the longer ID format looks like the following: <code>snap-78e226633445566ee</code>.</p> <p>For more information, see <a href="http://forums.aws.amazon.com/ann.jspa?annID=3557">Announcement: Heads-up – Longer Storage Gateway volume and snapshot IDs coming in 2016</a>.</p> </important>'
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: storagegateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/storagegateway-2013-06-30.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://storagegateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Storage Gateway multi-region endpoint
- url: https://storagegateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Storage Gateway multi-region endpoint
- url: http://storagegateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Storage Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://storagegateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Storage Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=StorageGateway 20130630.DescribeTapeArchives'
paths:
  /#X-Amz-Target=StorageGateway_20130630.DescribeTapeArchives:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DescribeTapeArchives
      description: <p>Returns a description of specified virtual tapes in the virtual tape shelf (VTS). This operation is only supported in the tape gateway type.</p> <p>If a specific <code>TapeARN</code> is not specified, Storage Gateway returns a description of all virtual tapes found in the VTS associated with your account.</p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeTapeArchivesOutput'
        '480':
          description: InvalidGatewayRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidGatewayRequestException'
        '481':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DescribeTapeArchivesInput'
      parameters:
      - name: Limit
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: Marker
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - StorageGateway_20130630.DescribeTapeArchives
      tags:
      - '#X Amz Target=StorageGateway 20130630.DescribeTapeArchives'
components:
  schemas:
    InternalServerError: {}
    TapeArchive:
      type: object
      properties:
        TapeARN:
          allOf:
          - $ref: '#/components/schemas/TapeARN'
          - description: The Amazon Resource Name (ARN) of an archived virtual tape.
        TapeBarcode:
          allOf:
          - $ref: '#/components/schemas/TapeBarcode'
          - description: The barcode that identifies the archived virtual tape.
        TapeCreatedDate:
          allOf:
          - $ref: '#/components/schemas/Time'
          - description: The date the virtual tape was created.
        TapeSizeInBytes:
          allOf:
          - $ref: '#/components/schemas/TapeSize'
          - description: The size, in bytes, of the archived virtual tape.
        CompletionTime:
          allOf:
          - $ref: '#/components/schemas/Time'
          - description: <p>The time that the archiving of the virtual tape was completed.</p> <p>The default timestamp format is in the ISO8601 extended YYYY-MM-DD'T'HH:MM:SS'Z' format.</p>
        RetrievedTo:
          allOf:
          - $ref: '#/components/schemas/GatewayARN'
          - description: <p>The Amazon Resource Name (ARN) of the tape gateway that the virtual tape is being retrieved to.</p> <p>The virtual tape is retrieved from the virtual tape shelf (VTS).</p>
        TapeStatus:
          allOf:
          - $ref: '#/components/schemas/TapeArchiveStatus'
          - description: The current state of the archived virtual tape.
        TapeUsedInBytes:
          allOf:
          - $ref: '#/components/schemas/TapeUsage'
          - description: <p>The size, in bytes, of data stored on the virtual tape.</p> <note> <p>This value is not available for tapes created prior to May 13, 2015.</p> </note>
        KMSKey:
          $ref: '#/components/schemas/KMSKey'
        PoolId:
          allOf:
          - $ref: '#/components/schemas/PoolId'
          - description: The ID of the pool that was used to archive the tape. The tapes in this pool are archived in the S3 storage class that is associated with the pool.
        Worm:
          allOf:
          - $ref: '#/components/schemas/boolean'
          - description: Set to <code>true</code> if the archived tape is stored as write-once-read-many (WORM).
        RetentionStartDate:
          allOf:
          - $ref: '#/components/schemas/Time'
          - description: If the archived tape is subject to tape retention lock, the date that the archived tape started being retained.
        PoolEntryDate:
          allOf:
          - $ref: '#/components/schemas/Time'
          - description: <p>The time that the tape entered the custom tape pool.</p> <p>The default timestamp format is in the ISO8601 extended YYYY-MM-DD'T'HH:MM:SS'Z' format.</p>
      description: Represents a virtual tape that is archived in the virtual tape shelf (VTS).
    DescribeTapeArchivesOutput:
      type: object
      example:
        Marker: '1'
        TapeArchives:
        - CompletionTime: 2016-12-16T13:50Z
          TapeARN: arn:aws:storagegateway:us-east-1:999999999:tape/AM08A1AD
          TapeBarcode: AM08A1AD
          TapeSizeInBytes: 107374182400
          TapeStatus: ARCHIVED
        - CompletionTime: 2016-12-16T13:59Z
          TapeARN: arn:aws:storagegateway:us-east-1:999999999:tape/AMZN01A2A4
          TapeBarcode: AMZN01A2A4
          TapeSizeInBytes: 429496729600
          TapeStatus: ARCHIVED
      properties:
        TapeArchives:
          allOf:
          - $ref: '#/components/schemas/TapeArchives'
          - description: An array of virtual tape objects in the virtual tape shelf (VTS). The description includes of the Amazon Resource Name (ARN) of the virtual tapes. The information returned includes the Amazon Resource Names (ARNs) of the tapes, size of the tapes, status of the tapes, progress of the description, and tape barcode.
        Marker:
          allOf:
          - $ref: '#/components/schemas/Marker'
          - description: An opaque string that indicates the position at which the virtual tapes that were fetched for description ended. Use this marker in your next request to fetch the next set of virtual tapes in the virtual tape shelf (VTS). If there are no more virtual tapes to describe, this field does not appear in the response.
      description: DescribeTapeArchivesOutput
    KMSKey:
      type: string
      pattern: (^arn:(aws|aws-cn|aws-us-gov):kms:([a-zA-Z0-9-]+):([0-9]+):(key|alias)/(\S+)$)|(^alias/(\S+)$)
      description: The Amazon Resource Name (ARN) of a symmetric customer master key (CMK) used for Amazon S3 server-side encryption. Storage Gateway does not support asymmetric CMKs. This value can only be set when <code>KMSEncrypted</code> is <code>true</code>. Optional.
      minLength: 7
      maxLength: 2048
    PositiveIntObject:
      type: integer
      minimum: 1
    TapeARN:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-us-gov):storagegateway:[a-z\-0-9]+:[0-9]+:tape\/[0-9A-Z]{5,16}$
      minLength: 50
      maxLength: 500
    boolean:
      type: boolean
    PoolId:
      type: string
      minLength: 1
      maxLength: 100
    TapeUsage:
      type: integer
    TapeSize:
      type: integer
    TapeARNs:
      type: array
      description: The Amazon Resource Name (ARN) of each of the tapes you want to list. If you don't specify a tape ARN, the response lists all tapes in both your VTL and VTS.
      items:
        $ref: '#/components/schemas/TapeARN'
    InvalidGatewayRequestException: {}
    GatewayARN:
      type: string
      description: The Amazon Resource Name (ARN) of the gateway. Use the <a>ListGateways</a> operation to return a list of gateways for your account and Amazon Web Services Region.
      minLength: 50
      maxLength: 500
    TapeArchiveStatus:
      type: string
    Time:
      type: string
      format: date-time
    DescribeTapeArchivesInput:
      type: object
      title: DescribeTapeArchivesInput
      properties:
        TapeARNs:
          allOf:
          - $ref: '#/components/schemas/TapeARNs'
          - description: Specifies one or more unique Amazon Resource Names (ARNs) that represent the virtual tapes you want to describe.
        Marker:
          allOf:
          - $ref: '#/components/schemas/Marker'
          - description: An opaque string that indicates the position at which to begin describing virtual tapes.
        Limit:
          allOf:
          - $ref: '#/components/schemas/PositiveIntObject'
          - description: Specifies that the number of virtual tapes described be limited to the specified number.
      description: DescribeTapeArchivesInput
    TapeBarcode:
      type: string
      pattern: ^[A-Z0-9]*$
      minLength: 5
      maxLength: 16
    TapeArchives:
      type: array
      items:
        $ref: '#/components/schemas/TapeArchive'
    Marker:
      type: string
      minLength: 1
      maxLength: 1000
  parameters:
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/storagegateway/
x-hasEquivalentPaths: true
