openapi: 3.1.0
info:
  title: 'Amazon Storage Gateway REST Amazon Storage Gateway REST API #X Amz Target=StorageGateway 20130630.DisassociateFileSystem API'
  description: AWS Storage Gateway is a hybrid cloud storage service that gives you on-premises access to virtually unlimited cloud storage. This API enables management of gateways, volumes, virtual tapes, file shares, and cached storage resources.
  version: '2013-06-30'
  contact:
    name: AWS Support
    url: https://aws.amazon.com/premiumsupport/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://aws.amazon.com/service-terms/
  x-logo:
    url: https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x630.png
servers:
- url: https://storagegateway.{region}.amazonaws.com
  description: Amazon Storage Gateway regional endpoint
  variables:
    region:
      default: us-east-1
      description: AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - eu-west-1
      - eu-west-2
      - eu-central-1
      - ap-northeast-1
      - ap-southeast-1
      - ap-southeast-2
      - ap-south-1
      - sa-east-1
security:
- sigv4: []
tags:
- name: '#X Amz Target=StorageGateway 20130630.DisassociateFileSystem'
paths:
  /#X-Amz-Target=StorageGateway_20130630.DisassociateFileSystem:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DisassociateFileSystem
      description: Disassociates an Amazon FSx file system from the specified gateway. After the disassociation process finishes, the gateway can no longer access the Amazon FSx file system. This operation is only supported in the FSx File Gateway type.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisassociateFileSystemOutput'
        '480':
          description: InvalidGatewayRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidGatewayRequestException'
        '481':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DisassociateFileSystemInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - StorageGateway_20130630.DisassociateFileSystem
      tags:
      - '#X Amz Target=StorageGateway 20130630.DisassociateFileSystem'
components:
  schemas:
    InternalServerError: {}
    boolean:
      type: boolean
    DisassociateFileSystemInput:
      type: object
      required:
      - FileSystemAssociationARN
      title: DisassociateFileSystemInput
      properties:
        FileSystemAssociationARN:
          allOf:
          - $ref: '#/components/schemas/FileSystemAssociationARN'
          - description: The Amazon Resource Name (ARN) of the file system association to be deleted.
        ForceDelete:
          allOf:
          - $ref: '#/components/schemas/boolean'
          - description: If this value is set to true, the operation disassociates an Amazon FSx file system immediately. It ends all data uploads to the file system, and the file system association enters the <code>FORCE_DELETING</code> status. If this value is set to false, the Amazon FSx file system does not disassociate until all data is uploaded.
    DisassociateFileSystemOutput:
      type: object
      properties:
        FileSystemAssociationARN:
          allOf:
          - $ref: '#/components/schemas/FileSystemAssociationARN'
          - description: The Amazon Resource Name (ARN) of the deleted file system association.
    InvalidGatewayRequestException: {}
    FileSystemAssociationARN:
      type: string
      minLength: 50
      maxLength: 500
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    sigv4:
      type: apiKey
      name: Authorization
      in: header
      description: AWS Signature Version 4
externalDocs:
  description: Amazon Storage Gateway API Reference
  url: https://docs.aws.amazon.com/storagegateway/latest/APIReference/Welcome.html
