openapi: 3.2.0
info:
  version: '2013-06-30'
  x-release: v4
  title: 'AWS Storage Gateway #X Amz Target=StorageGateway…'
  description: 'Storage Gateway Service

    Storage Gateway is the service that connects an on-premises software appliance with cloud-based storage to provide seamless and secure integration between an organization''s on-premises IT environment and the Amazon Web Services storage infrastructure.'
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: storagegateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/storagegateway-2013-06-30.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://storagegateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Storage Gateway multi-region endpoint
- url: https://storagegateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Storage Gateway multi-region endpoint
- url: http://storagegateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Storage Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://storagegateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Storage Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=StorageGateway 20130630.AssociateFileSystem'
paths:
  /#X-Amz-Target=StorageGateway_20130630.AssociateFileSystem:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: AssociateFileSystem
      description: Associate an Amazon FSx file system with the FSx File Gateway. After the association process is complete, the file shares on the Amazon FSx file system are available for access through the gateway. This operation only supports the FSx File Gateway type.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssociateFileSystemOutput'
        '480':
          description: InvalidGatewayRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidGatewayRequestException'
        '481':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssociateFileSystemInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - StorageGateway_20130630.AssociateFileSystem
      tags:
      - '#X Amz Target=StorageGateway 20130630.AssociateFileSystem'
      summary: Associate file system
      x-summary-source: derived
components:
  schemas:
    TagKey:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 1
      maxLength: 128
    CacheAttributes:
      type: object
      properties:
        CacheStaleTimeoutInSeconds:
          allOf:
          - $ref: '#/components/schemas/CacheStaleTimeoutInSeconds'
          - description: <p>Refreshes a file share's cache by using Time To Live (TTL). TTL is the length of time since the last refresh after which access to the directory would cause the file gateway to first refresh that directory's contents from the Amazon S3 bucket or Amazon FSx file system. The TTL duration is in seconds.</p> <p>Valid Values:0, 300 to 2,592,000 seconds (5 minutes to 30 days)</p>
      description: The refresh cache information for the file share or FSx file systems.
    FileSystemLocationARN:
      type: string
      minLength: 8
      maxLength: 512
    IpAddressList:
      type: array
      items:
        $ref: '#/components/schemas/IPV4Address'
      minItems: 0
      maxItems: 1
    TagValue:
      type: string
      maxLength: 256
    EndpointNetworkConfiguration:
      type: object
      properties:
        IpAddresses:
          allOf:
          - $ref: '#/components/schemas/IpAddressList'
          - description: <p>A list of gateway IP addresses on which the associated Amazon FSx file system is available.</p> <note> <p>If multiple file systems are associated with this gateway, this field is required.</p> </note>
      description: Specifies network configuration information for the gateway associated with the Amazon FSx file system.
    Tag:
      type: object
      required:
      - Key
      - Value
      properties:
        Key:
          allOf:
          - $ref: '#/components/schemas/TagKey'
          - description: Tag key. The key can't start with aws:.
        Value:
          allOf:
          - $ref: '#/components/schemas/TagValue'
          - description: Value of the tag key.
      description: 'A key-value pair that helps you manage, filter, and search for your resource. Allowed characters: letters, white space, and numbers, representable in UTF-8, and the following characters: + - = . _ : /.'
    AssociateFileSystemOutput:
      type: object
      properties:
        FileSystemAssociationARN:
          allOf:
          - $ref: '#/components/schemas/FileSystemAssociationARN'
          - description: The ARN of the newly created file system association.
    IPV4Address:
      type: string
      pattern: ^((25[0-5]|(2[0-4]|1[0-9]|[1-9]|)[0-9])(\.(?!$)|$)){4}
      minLength: 7
      maxLength: 15
    Tags:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    InternalServerError: {}
    FileSystemAssociationARN:
      type: string
      minLength: 50
      maxLength: 500
    AuditDestinationARN:
      type: string
      maxLength: 1024
    DomainUserName:
      type: string
      pattern: ^\w[\w\.\- ]*$
      minLength: 1
      maxLength: 1024
    ClientToken:
      type: string
      minLength: 5
      maxLength: 100
    DomainUserPassword:
      type: string
      pattern: ^[ -~]+$
      minLength: 1
      maxLength: 1024
      format: password
    AssociateFileSystemInput:
      type: object
      required:
      - UserName
      - Password
      - ClientToken
      - GatewayARN
      - LocationARN
      title: AssociateFileSystemInput
      properties:
        UserName:
          allOf:
          - $ref: '#/components/schemas/DomainUserName'
          - description: The user name of the user credential that has permission to access the root share D$ of the Amazon FSx file system. The user account must belong to the Amazon FSx delegated admin user group.
        Password:
          allOf:
          - $ref: '#/components/schemas/DomainUserPassword'
          - description: The password of the user credential.
        ClientToken:
          allOf:
          - $ref: '#/components/schemas/ClientToken'
          - description: A unique string value that you supply that is used by the FSx File Gateway to ensure idempotent file system association creation.
        GatewayARN:
          $ref: '#/components/schemas/GatewayARN'
        LocationARN:
          allOf:
          - $ref: '#/components/schemas/FileSystemLocationARN'
          - description: The Amazon Resource Name (ARN) of the Amazon FSx file system to associate with the FSx File Gateway.
        Tags:
          allOf:
          - $ref: '#/components/schemas/Tags'
          - description: A list of up to 50 tags that can be assigned to the file system association. Each tag is a key-value pair.
        AuditDestinationARN:
          allOf:
          - $ref: '#/components/schemas/AuditDestinationARN'
          - description: The Amazon Resource Name (ARN) of the storage used for the audit logs.
        CacheAttributes:
          $ref: '#/components/schemas/CacheAttributes'
        EndpointNetworkConfiguration:
          allOf:
          - $ref: '#/components/schemas/EndpointNetworkConfiguration'
          - description: <p>Specifies the network configuration information for the gateway associated with the Amazon FSx file system.</p> <note> <p>If multiple file systems are associated with this gateway, this parameter's <code>IpAddresses</code> field is required.</p> </note>
    GatewayARN:
      type: string
      description: The Amazon Resource Name (ARN) of the gateway. Use the <a>ListGateways</a> operation to return a list of gateways for your account and Amazon Web Services Region.
      minLength: 50
      maxLength: 500
    InvalidGatewayRequestException: {}
    CacheStaleTimeoutInSeconds:
      type: integer
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/storagegateway/
x-hasEquivalentPaths: true
